# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('qualification', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('eject_field', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_choice', models.CharField(max_length=50)),
                ('question', models.PositiveSmallIntegerField()),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('marks', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question'),
        ),
    ]
