# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170625_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default=datetime.datetime(2017, 6, 25, 14, 16, 8, 263000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default=datetime.datetime(2017, 6, 25, 14, 16, 27, 566000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(default=datetime.datetime(2017, 6, 25, 14, 16, 30, 75000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
