# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_choice',
            name='question',
        ),
        migrations.AddField(
            model_name='candidate_choice',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
