# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20170711_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_choice',
            name='marks',
        ),
        migrations.AddField(
            model_name='candidate',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate_choice',
            name='candidate_answer',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate_choice',
            name='candidate_choice',
            field=models.CharField(max_length=200),
        ),
    ]
