# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_candidate_choice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_choice',
            name='status',
            field=models.CharField(default='Not Attended', max_length=10),
        ),
    ]
