# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_candidate_choice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_choice',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate_choice',
            name='candidate_question',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
