# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20170716_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_choice',
            name='status',
        ),
    ]
