# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_question_eject_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
